name: deploy_lambda

on:
  push:
    branches:
      - development
      - main

jobs:
  deploy_stock_search:
    name: deploy stock search lambda function
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./stock-search
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Install Serverless
        run: npm install -g serverless

      - name: Install npm dependencies
        run: npm ci

      - name: Deploy function
        run: |
          npx ncc build index.ts
          zip -j deploy.zip ./dist/*
          aws lambda update-function-code --function-name=stockSearch --zip-file=fileb://deploy.zip

  deploy_stock_overview:
    name: deploy stock overview lambda function
    runs-on: ubuntu-latest
    defaults:
      run:
          working-directory: ./stock-overview
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Deploy function
        run: |
            zip -r deploy.zip .
            aws lambda update-function-code --function-name=stockOverview --zip-file=fileb://deploy.zip