name: deploy_lambda

on:
    push:
        branches:
            - main

jobs:
    deploy_stock_search:
        name: deploy stock search lambda function
        runs-on: ubuntu-latest
        steps: 
            - name: checkout source code
              uses: actions/checkout
            - name: install node
              uses: actions/setup-node
              with:
                node-version: "20.x"
            - name: npm install
              env: 
                CI: true
              run:
                npm ci