name: deploy_lambda

on:
    push:
        branches:
            - main

jobs:
    deploy_stock_search:
        name: deploy stock search lambda function
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout source code
              uses: actions/checkout@v2

            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                node-version: "20.x"

            - name: Change directory to stock-search
              run: cd stock-search

            - name: Install Serverless
              run: npm install -g serverless
              working-directory: ./stock-search

            - name: Install npm dependencies
              run: npm ci
              working-directory: ./stock-search


