name: Tests

on:
  push:
    paths:
      - stock-search/
      - .github/workflows/**

jobs:

  stock_search_test:
    
    name: Test Stock Search
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./stock-search
    steps:
        - name: Checkout source code
          uses: actions/checkout@v3

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4     
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ca-central-1

        - name: Install modules
          run: yarn
          
        - name: Run tests
          run: yarn test