name: Tests

on:
  push:
    paths:
      - stock-search/**
      - watchlist-service/**
      - .github/workflows/**

jobs:

  stock_search_test:
    
    name: Test Stock Search
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./stock-search
    steps:
        - name: Checkout source code
          uses: actions/checkout@v4

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4     
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ca-central-1

        - name: Install modules
          run: yarn
          
        - name: Run tests
          run: yarn test
  
  watchlist_service_test:
    name: Test Watchlist Service
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./watchlist-service  

    steps:
        - name: Checkout source code
          uses: actions/checkout@v4

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
            cache: 'pip'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Test with pytest
          env:
            SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
            SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
            TEST_USER_ID: ${{ secrets.TEST_USER_ID }}
          run: |
            pip install pytest pytest-cov
            pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

                

